### ISSUE TITLE
リストにユーザを一括で追加する際にエラーが発生する

### ISSUE THREAD

**Issue by silverag-corgi** [silverag-corgi/twitter-app#2]
1. エラー
    - リストメンバー数の小計が期待値未満であったため異常終了した
        - 小計：26/50人
        - 合計(list_.member_count)：76/162人
    - TwitterWebアプリ、非公式クライアントでリストにユーザを24時間追加できない
        - TwitterWebアプリ
            - ユーザの追加を試行した後に更新するとユーザが追加されていない
        - 非公式クライアント(ツイタマ)
            - ユーザの追加を試行するとエラーメッセージが表示される
            - エラー 403: You aren't allowed to add members to this list.

2. 実行プログラム
    - コミット
        - a8d9004
    - Pythonスクリプト
        - list-imp (twitter_list_import.py)
    - エンドポイント
        - POST lists/members/create_all
    - 処理概要
        1. ファイルからユーザIDを読み込む
        1. 読み込んだユーザIDから下記アカウントを除外する
            - 削除されたアカウント
            - 凍結されたアカウント
            - 保護されたアカウント
            - 自分をブロックしたアカウント
            - 自分がブロックしたアカウント
        1. 当該ユーザIDを50人ごとに分割する
        1. 15分ごとに一括で追加する

3. 実行ログ
    ```cmd
    > poetry run list-imp
    [INF][                  twitter_list_import.py:0043][                                       main] 実行コマンド：['list-imp']
    [INF][                     twitter_api_auth.py:0019][ do_logic_that_generate_api_by_oauth_1_user] TwitterAPI認証を開始します。
    [INF][                     twitter_api_auth.py:0102][                __get_twitter_api_auth_info] TwitterAPI認証情報取得に成功しました。
    [INF][                twitter_api_auth_util.py:0137][               generate_api_by_oauth_1_user] API生成(OAuth 1.0a - User Access Tokens)に成功しました。
    [INF][                     twitter_api_auth.py:0028][ do_logic_that_generate_api_by_oauth_1_user] TwitterAPI認証を終了します。
    [INF][                  twitter_list_import.py:0030][                                   do_logic] Twitterリストインポートを開始します。
    [INF][                   twitter_users_util.py:0448][                                  get_lists] リスト(複数)取得に成功しました。(user_id:)
    [INF][                   twitter_users_util.py:0590][                              generate_list] リスト生成に成功しました。(list_name:_2022-03_全て_100周以上)
    [INF][                   twitter_users_util.py:0321][                               lookup_users] ユーザ検索に成功しました。
    [INF][                   twitter_users_util.py:0909][__split_users_into_no_problems_and_problems] 削除されたアカウント、凍結されたアカウント、保護されたアカウントの除外に成功しました。
    [INF][                   twitter_users_util.py:0910][__split_users_into_no_problems_and_problems] 時間がかかるため気長にお待ちください。
    [INF][                   twitter_users_util.py:1004][                         get_auth_user_info] 認証ユーザ情報取得に成功しました。(user_id:silverag_corgi , user_name:Rem_)
    [INF][                   twitter_users_util.py:0920][__split_users_into_no_problems_and_problems] 自分をブロックしたアカウントの除外に成功しました。
    [INF][                   twitter_users_util.py:1086][                    get_blocked_users_pages] ブロックユーザページ取得に成功しました。
    [INF][                   twitter_users_util.py:0935][__split_users_into_no_problems_and_problems] 自分がブロックしたアカウントの除外に成功しました。
    [INF][                   twitter_users_util.py:0946][__split_users_into_no_problems_and_problems] ユーザの分割に成功しました。
    [INF][                   twitter_users_util.py:0766][                          add_users_to_list] 下記ユーザは問題があるため除外しました。(num_of_users_with_problems:3)
    [INF][                   twitter_users_util.py:0768][                          add_users_to_list] ユーザID：['aaaaa', 'bbbbb', 'ccccc']
    [INF][                   twitter_users_util.py:0769][                          add_users_to_list] ユーザ名：['-', '-', '-']
    [INF][                   twitter_users_util.py:0770][                          add_users_to_list] 50人ごとにユーザを追加します。(num_of_users_without_problems:162)
    [INF][                             __init__.py:0028][                   show_estimated_proc_time] 想定処理時間：約60分(TwitterAPIのレート制限により処理に時間がかかります)
    [INF][                   twitter_users_util.py:0796][                          add_users_to_list] ユーザを追加しました。(num_of_users_at_this_time:50/50, sum_of_users_at_this_time:50/162)
    [INF][                   twitter_users_util.py:0812][                          add_users_to_list] 15分後(2022-04-20 08:36:41)に後続の処理を実行します。
    [INF][                   twitter_users_util.py:0796][                          add_users_to_list] ユーザを追加しました。(num_of_users_at_this_time:26/50, sum_of_users_at_this_time:76/162)
    [ERR][                   twitter_users_util.py:0817][                          add_users_to_list] ユーザ(複数)追加に失敗しました。
    [INF][                   twitter_users_util.py:0448][                                  get_lists] リスト(複数)取得に成功しました。(user_id:)
    [ERR][                   twitter_users_util.py:0653][                               destroy_list] リスト破棄に失敗しました。(list_name:_2022-03_全て_100周以上)
    [INF][                  twitter_list_import.py:0081][                                   do_logic] Twitterリストインポートを終了します。
    [ERR][                               logger.py:0153][                                    log_exc] 
    Traceback (most recent call last):
      File "C:\Git\python\twitter-app\src\twitter_app\logic\twitter_list_import.py", line 65, in do_logic
        twitter_users_util.add_users_to_list(
      File "C:\Git\python\twitter-app\src\twitter_app\util\twitter_api_v1_1\standard\twitter_users_util.py", line 818, in add_users_to_list
        raise(e)
      File "C:\Git\python\twitter-app\src\twitter_app\util\twitter_api_v1_1\standard\twitter_users_util.py", line 805, in add_users_to_list
        raise(pyl.CustomError(f'HTTPステータスコードが正常(2xx)以外の可能性があります。'))
    python_lib_for_me.exception.CustomError: HTTPステータスコードが正常(2xx)以外の可能性があります。
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Git\python\twitter-app\src\twitter_app\main\twitter_list_import.py", line 54, in main
        twitter_list_import.do_logic(
      File "C:\Git\python\twitter-app\src\twitter_app\logic\twitter_list_import.py", line 77, in do_logic
        twitter_users_util.destroy_list(api, list_.name)
      File "C:\Git\python\twitter-app\src\twitter_app\util\twitter_api_v1_1\standard\twitter_users_util.py", line 654, in destroy_list
        raise(e)
      File "C:\Git\python\twitter-app\src\twitter_app\util\twitter_api_v1_1\standard\twitter_users_util.py", line 648, in destroy_list
        api.destroy_list(list_id=list.id)
      File "C:\Git\python\twitter-app\.venv\lib\site-packages\tweepy\api.py", line 46, in wrapper
        return method(*args, **kwargs)
      File "C:\Git\python\twitter-app\.venv\lib\site-packages\tweepy\api.py", line 1749, in destroy_list
        return self.request(
      File "C:\Git\python\twitter-app\.venv\lib\site-packages\tweepy\api.py", line 261, in request
        raise NotFound(resp)
    tweepy.errors.NotFound: 404 Not Found
    34 - Sorry, that page does not exist.
    ```

**Comment by silverag-corgi** [comment]
短時間に多くのユーザを追加したため本エラーが発生したと仮定し、
安定した追加処理を実現するため以下をパラメータとして検証した。

- ユーザ数／追加
- 時間間隔／追加

検証結果を下記図に示す。
なお、エラー403によるリスト追加エラーが解除されるのは24時間後であるため、
前回分が終了してから24時間後に実行する。

![Screenshot_00001](https://user-images.githubusercontent.com/48097959/167631691-6e4dcae1-a379-4732-820b-5fcf32b68b2f.JPG)

その結果、下記パラメータが最善であると判断した。

- ユーザ数／日：100人
    - ユーザ数／追加：50人
    - 追加／日：2回
- 時間間隔／追加：30分

また、もし追加する際に処理が中断された場合は、1日後に下記オプションを指定して再度実行する。

- 差分ユーザ追加 (差分のあるユーザのみを追加する)

**Comment by silverag-corgi** [comment]
コミット ee5e85e で修正した。
